import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const Arrow=()=> <span className="arrow">↗</span>;
const menu=[['Espresso','Double shot · house roast','$3.50'],['Maple Oat Latte','Espresso · oat milk · maple','$6.25'],['Cinnamon Morning Bun','Brown sugar · cinnamon · orange glaze','$5.00'],['Harissa Egg Toast','Soft egg · harissa · sourdough · herbs','$12.50']];
const reviews=[['“','The kind of café you accidentally spend three hours in. The coffee is excellent, the room is beautiful, and nobody rushes you.','— Nina R.'],['“','Best morning ritual in the neighborhood. Their maple oat latte and morning bun are basically a required combination.','— Daniel K.']];
function App(){
 const[open,setOpen]=useState(false); const[tab,setTab]=useState('Coffee');
 const go=id=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setOpen(false)};
 return <div className="site">
  <div className="announcement">NOW POURING: OUR AUTUMN HOUSE ROAST <span>·</span> OPEN DAILY 7AM–5PM</div>
  <header><button className="brand" onClick={()=>go('home')}><span className="bean">●</span><span><b>EMBER</b><i>&amp; BEAN</i></span></button><button className="hamb" onClick={()=>setOpen(!open)}>{open?'×':'☰'}</button>
   <nav className={open?'open':''}><button onClick={()=>go('menu')}>Menu</button><button onClick={()=>go('story')}>Our Story</button><button onClick={()=>go('visit')}>Visit</button><button className="reserve" onClick={()=>go('visit')}>Find a Table <Arrow/></button></nav>
  </header>
  <main>
   <section id="home" className="hero"><div className="heroPaper"><div className="stamp">PORTLAND<br/><strong>OR</strong><br/>EST. 2018</div><div className="heroCopy"><p className="eyebrow">COFFEE · BREAKFAST · BAKERY</p><h1>Good coffee.<br/><em>Good moments.</em></h1><p className="lead">A neighborhood café for slow mornings, quick catch-ups, and the little rituals that make a day feel like yours.</p><div className="heroActions"><button className="dark" onClick={()=>go('menu')}>Explore the menu <Arrow/></button><button className="textBtn" onClick={()=>go('visit')}>Find us <Arrow/></button></div></div><div className="cupArt"><div className="sunDisc"/><div className="cup"><div className="coffee"/><div className="steam s1"/><div className="steam s2"/><div className="handle"/></div><div className="saucer"/><span className="note">ROASTED<br/>IN HOUSE</span></div></div></section>
   <div className="ticker"><span>SMALL BATCH ROASTS</span><b>✦</b><span>SEASONAL BAKES</span><b>✦</b><span>LOCALLY SOURCED</span><b>✦</b><span>COME AS YOU ARE</span></div>
   <section id="menu" className="section menuSection"><div className="sectionIntro"><p className="eyebrow">— WHAT'S ON THE TABLE</p><h2>Made for your<br/><em>kind of morning.</em></h2><p>Our menu changes with the seasons, but the idea stays the same: simple ingredients, careful preparation, nothing fussy.</p></div><div className="menuBox"><div className="tabs">{['Coffee','Breakfast','Bakery'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="menuItems">{menu.map((m,i)=><article><span className="num">0{i+1}</span><div><h3>{m[0]}</h3><p>{m[1]}</p></div><strong>{m[2]}</strong></article>)}</div><button className="fullMenu">View full menu <Arrow/></button></div></section>
   <section id="story" className="story"><div className="storyArt"><div className="arch"><div className="archWindow"><span>EB</span></div></div><div className="leaf l1"/><div className="leaf l2"/></div><div className="storyCopy"><p className="eyebrow">— OUR STORY</p><h2>Built around<br/><em>the pause.</em></h2><p>Ember &amp; Bean started with a simple belief: coffee tastes better when you have somewhere worth sitting.</p><p>So we built a little room around the ritual — warm light, good records, tables made for lingering, and food that feels like someone cared.</p><div className="signature">Mara &amp; Jules <span>founders</span></div></div></section>
   <section className="special"><div><p className="eyebrow">TODAY'S SPECIAL</p><h2>Honey-cardamom<br/><em>morning bun.</em></h2><p>Buttery laminated dough, cardamom sugar, local honey and a little sea salt. Best before noon.</p><button className="creamBtn" onClick={()=>go('visit')}>Come try it <Arrow/></button></div><div className="bunArt"><div className="plate"/><div className="bun"><span/><span/><span/></div></div></section>
   <section className="reviews"><div className="sectionIntro"><p className="eyebrow">— KIND WORDS</p><h2>Come for coffee.<br/><em>Stay for the feeling.</em></h2></div><div className="reviewGrid">{reviews.map(r=><article><span className="quote">{r[0]}</span><blockquote>{r[1]}</blockquote><small>{r[2]}</small></article>)}</div></section>
   <section id="visit" className="visit"><div className="visitInfo"><p className="eyebrow">— COME BY</p><h2>Your table<br/><em>is waiting.</em></h2><p>1842 SE Hawthorne Blvd<br/>Portland, Oregon 97214</p><div className="hours"><b>MON–FRI <span>7:00 AM — 5:00 PM</span></b><b>SAT–SUN <span>8:00 AM — 5:00 PM</span></b></div><button className="dark" onClick={()=>window.location.href='tel:+15035550184'}>Call (503) 555-0184 <Arrow/></button></div><div className="mapCard"><div className="mapGrid"/><div className="pin">EB</div><div className="mapLabel">EMBER &amp; BEAN<br/><small>HAWTHORNE DISTRICT</small></div></div></section>
   <section className="newsletter"><p className="eyebrow">A LITTLE SOMETHING IN YOUR INBOX</p><h2>Seasonal things,<br/><em>sent occasionally.</em></h2><form onSubmit={e=>e.preventDefault()}><input type="email" placeholder="your@email.com"/><button>Join the list <Arrow/></button></form><small>No spam. Just new roasts, specials and good excuses to stop by.</small></section>
  </main>
  <footer><div className="footerTop"><div className="brand"><span className="bean">●</span><span><b>EMBER</b><i>&amp; BEAN</i></span></div><p>Good coffee. Good food.<br/>Good moments.</p><div><a href="#menu">Menu</a><a href="#story">Story</a><a href="#visit">Visit</a></div></div><div className="footerBottom">© 2026 Ember &amp; Bean · Concept project by Adarsh · Fictional business for portfolio demonstration</div></footer>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);